### ISSUE TITLE
Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by reaurr** [ashwio/arm64-hypervisor-tutorial#2]
Hi,
Im trying to compile project, but I got this following error : 
```
make all CROSS_COMPILE="/home/pi/gcc-linaro-aarch64-elf/bin/aarch64-elf-"

Syntax error: word unexpected (expecting ")")
make: *** [Makefile:77: out/main.o] Error 2
```
on Makefile 77's line is : 
`$(CC) $(CC_FLAGS) -c $< -o $@`

Im using RasperryPi 

Any suggestions are welcome.
Thank you.

**Comment by reaurr** [comment]
I was using linaro x64 toolchain, therefore it wasnt compile. Switching rasp to x64, it compiles.

**Comment by ashwio** [comment]
Hi,

Glad to see you were able to resolve this yourself. Out of interest, which version of the Linaro toolchain were you using when you faced the build error?

I can successfully build using `aarch64-elf-gcc (Linaro GCC 7.5-2019.12) 7.5.0` [directly from Linaro](http://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-elf/) and using `aarch64-linux-gnu-gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0` from the Ubuntu 18.04 package repos.

Were you using an older version?
